import type { Metadata } from "next";
import { Montserrat, Geist_Mono } from "next/font/google";
import "./globals.css";
import AccessibilityMenuWrapper from "@/components/Accessibility/AccessibiltyWrapper";
import { VoiceNavigationDockComponent } from "@/components/voice-navigation-dock";
import { AuthProvider } from "@/context/AuthContext";
import { Toaster } from "@/components/ui/toaster";

const montserrat = Montserrat({
  variable: "--font-montserrat",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${montserrat.variable} ${geistMono.variable} antialiased font-sans`}
      >
        <AccessibilityMenuWrapper>
          <VoiceNavigationDockComponent />
          <Toaster />
          <AuthProvider>
            {children}
          </AuthProvider>
        </AccessibilityMenuWrapper>
      </body>
    </html>
  );
}
